name: Auto-Join Google Meet

on:
  schedule:
    # 4:30 AM PT during DST ≈ 11:30 UTC; change if needed
    - cron: "30 11 * * *"
  workflow_dispatch: {}   # lets you run it manually from the Actions tab
  # (Optional) uncomment to run on every push:
  # push: {}

jobs:
  join:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Meet bot (headless)
        env:
          MEET_URL: ${{ secrets.MEET_URL }}
          GUEST_NAME: ${{ secrets.GUEST_NAME }}
          LEAVE_AFTER_MINUTES: "1"
        run: python meet_auto_join.py
